import docker
import tarfile
import io
import os

class Node():
    """!
    @brief Node base class.

    This class represents a generic node. It is a superclass for Hosts, Routers, etc.
    """

    __interfaces: List[(str, str)] # List of the (interface, network) tuples
    __container  # This is the container object returned by the docker API
    __containerName: str   # The corresponding container name


    def runCommand(cmd: str) -> int: 
        """!
        @brief Run a command on the node.

        Call docker::exec_run()

        @return Return the status of the command.
        """
        return 

    def copyFileToContainer(src_path: str, dest_dir: str) -> int:
        """!
        @brief Copy files to the container

        In the Docker SDK for Python, there is no single method literally named
        "copy." Instead, copying files is handled via two "Archive" methods.
        This is because the underlying Docker Engine API uses tar archives to
        stream files to and from containers.
        """

        # Code generated by AI, not tested yet.

        # Create a Tar archive in memory
        tar_stream = io.BytesIO()
        with tarfile.open(fileobj=tar_stream, mode='w') as tar:
            tar.add(src_path, arcname=os.path.basename(src_path))
        tar_stream.seek(0)

        # Use put_archive to send it to the container
        # The 'path' in put_archive is the destination DIRECTORY
        __container.put_archive(path=dest_dir, data=tar_stream)

        return 

    def copyFileFromContainer(src_path: str, dest_dir: str) -> int:
        """!
        @brief Copy files from the container

        """
        # Code generated by AI, not tested yet.

        # Get the archive stream
        stream, stat = __container.get_archive(src_path)
    
        # Save the stream to a local tar file
        with open("temp_archive.tar", "wb") as f:
            for chunk in stream:
                f.write(chunk)
    
        # (Optional) Extract the tar to get the actual file
        with tarfile.open("temp_archive.tar") as tar:
            tar.extractall(path=local_dest_path)
    
        os.remove("temp_archive.tar")

        return 
        

    def start(): 
        """!
        @brief Start the container.
        """
        return 

    def stop():
        """!
        @brief Stop the container.
        """
        return

    def restart():
        """!
        @brief Restart the container. 
        """
        return 

    def joinNetwork(network:str, ip='auto', dynamic=False):
        """!
        @brief Let the node container join a network. 

        This can be done while the container is still running.
        """
        return 

    def getIpAddresses() -> Dict[interface, ip]: 
        """!
        @brief Get the IP addresses of all the interfaces
        """
        return 
    
    def captureTraffic(interface: str, duration: int, file_path: str):
        """!
        @brief Start the traffic capture program (running tcpdump). 

        The captured data (pcap file) will be saved, and can be retrieved later.
        Note: we might want to use tshark, instead of tcpdump; its primary advantage 
        over tcpdump is its ability to extract specific protocol fields (like HTTP URLs, 
        DNS queries, or OSPF states) directly into structured formats.


        @return Return the status of the command
        """
        return 
        

    def addStaticRoute(destination: str, gateway: str): int 
        """!
        @brief Add a static route to the node's routing table

        @return Return the status of the command
        """
        return 

    def getRoutingTable(format='json', details=True) -> str
        """!
        @brief Get the result of 'ip -j --route' command (-j means JSON output)

        @return Return the JSON string (by default) or the normal output (without -j) 
        """
        return 

    def setLatency(interface: str, delay_ms: int, jitter_ms: int = 0):
        """!
        @brief Set the network latency on an interface 
        """
        return 

    def setPacketLoss(interface: str, percentage: float):
        """!
        @brief Set the packet loss on a network 
        """
        return 

    def setBandwidth(interface: str, limit: str):
        """!
        @brief Set the network bandwidth
        """
        return 

    def getQoSConfig(interface: str) -> Dict:
        """!
        @brief Get the OoS setup on the interface (latency, delay, and bandwith)
        """ 
        return

    def clearTrafficControlRules(interface: str):
        """!
        @brief Clean the traffic control rules 
        """
        return

